package br.com.cwi.crescer.melevaai.domain;

public enum Marca {
    AUDI, BMW, CHERY, CHEVROLET, CHRYSLER, CITROEN, DODGE, EFFA, FIAT, FORD, GEELY, HONDA, HYUNDAI, JAC, JEEP, KIA, LAND_ROVER, LEXUS, LIFAN, MERCEDES_BENZ, MITSUBISHI, NISSAN, PEUGEOT, RENAULT, SEAT, SMART, SSANGYONG, SUBARU, SUZUKI, TOYOTA, VOLKSWAGEN, VOLVO;
}
